### ISSUE TITLE
"easy" is unfriendly verbiage

### ISSUE THREAD

**Issue by jasonrose** [mylittlelambda/website#2]
https://github.com/mylittlelambda/website/blob/master/index.html#L84

might turn off people who have tried before and don't agree that FP is easy

**Comment by rtorr** [comment]
Great idea

**Comment by rtorr** [comment]
fixed: https://github.com/mylittlelambda/website/commit/1bb06c9ea0fe05b63b49da8af5ed121f62b697a2
